version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/openjdk:18.0.2
    steps:
      - checkout
      - run: java --version
      - run: gradle clean build
    