version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: gradle:jdk11
    steps:
      - checkout
      - run: java --version
      - run: gradle clean build  