workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      
jobs:
  test:
    docker:
      - image: gradle:jdk18
    steps:
      - checkout
      - run: java --version
      - run: gradle --version