version: 2.1

workflows:
  test-deploy:
    jobs:
      - test
      - demo

jobs:
  test:
    docker:
      - image: gradle:jdk18
    steps:
      - checkout
      - run: java --version
      - run: gradle --version 

  demo: 
    docker:
      - image: cimg/python
    steps: 
      - checkout
      - run: python --version